### ISSUE TITLE
Reviews of design doc

### ISSUE THREAD

**Issue by aracpyon** [marikasanuki/Ingenious#1]
Great job on design docs, Mari! Here are my reviews

**MVPs**
- [x] MVP 2: make sure to have a demo login
- [x] MVP 3: What is the index page for tracks? The chart of tracks or featured tracks? Let's think about how users access to the individual track. 
- [x] MVP 3: Can track be edited or deleted? -- ex. can lyrics be edited by any user?
- [x] MVP 4: Make sure you have full CRUD functionality for this MVP.

**Schema**
- [x] Add `created_at` and `updated_at` on each table
- [x] `Tracks` : Are you planning to make artist show page and would artist have a bio on their show page?  If so, add a new table called `artists` with columns of `id`, `name`, `bio`, `created at`,  `updated_at`, and add a foreign_key of `artist_id` to `Tracks` .
- [x]  `Likes`: Is this for upvotes? If so, let's change the name to `upvotes` just to be more semantic. 
- [x] `Likes` : Think about `polymorphism` for this table. (reference from Art API project's `like` table). Add a foreign key for `annotation` because you can do upvotes on annotations as well. That way, you don't need a foreign key `track_id` because `annotation` has `track_id` already.
- [x] `Likes`: (optional) if you want to add likes on comments, add `comment_id` as well, but this is last thing to consider while you are working on `upvotes`.

**Comment by marikasanuki** [comment]
Thanks for all your notes and suggestions, Ara! I made the changes and will reflect them in my Sample State

**Comment by aracpyon** [comment]
**Slate**
Great job on sample slate, Mari! Your changes on schema did reflect on your slate. For the suggestions you already worked on, you can mark on the little square blank. That way we can update each other. (For example, I clicked on the first suggestion in the schema section).
