### ISSUE TITLE
Backend routes and frontend routes

### ISSUE THREAD

**Issue by aracpyon** [marikasanuki/Ingenious#2]
Great job Mari! Here are my feedback: 

* One question: can any logged in user update or fix the annotation other users wrote on your app? 

**backend routes**
Looks food so far!

**Frontend routes**
Looks good so far. Another question: are you going to make artist show page?

**Comment by marikasanuki** [comment]
> can any logged in user update or fix the annotation other users wrote on your app?
Nope, just their own!

> are you going to make artist show page?
Not to start—I have artist show pages listed under Bonus 2.
