### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by marikasanuki** [marikasanuki/Ingenious#3]
- [x] Demo log in account provided
- [x] User can sign up with a new guest account
- [x] User can log in with a previously made account
- [x] User can log out from a previously made account

**Comment by aracpyon** [comment]
Hi Mari! It looks great so far! Awesome jobs. Here are my reviews:

- [ ] Error handling. Real website has this nice error handling. You should have it too. There are two designs on Genius:
  - [ ] First error handing is when you don't put all the information in the form
![Screen Shot 2020-06-08 at 8 46 36 AM (2)](https://user-images.githubusercontent.com/56740477/84032053-bb27e880-a964-11ea-89ec-aefe95f5c803.png)
  - [ ] second error handling is when the user logs in with a wrong information.
![Screen Shot 2020-06-08 at 8 48 45 AM (2)](https://user-images.githubusercontent.com/56740477/84032263-0d690980-a965-11ea-9d36-5d3e5df8fca7.png)
